package netutil

import "context"

// requestCorrelationIDKey carries a caller-owned opaque correlation value
// through downloader attempts. It is intentionally a context value so the
// downloader remains independent from topology and API packages.
type requestCorrelationIDKey struct{}

// WithRequestCorrelationID attaches an opaque, non-secret correlation ID to a
// request context. The value is emitted only in bounded attempt observations.
func WithRequestCorrelationID(ctx context.Context, id string) context.Context {
	if ctx == nil {
		ctx = context.Background()
	}
	if !validRequestCorrelationID(id) {
		return ctx
	}
	return context.WithValue(ctx, requestCorrelationIDKey{}, id)
}

// RequestCorrelationID returns the opaque correlation value attached to ctx.
func RequestCorrelationID(ctx context.Context) string {
	if ctx == nil {
		return ""
	}
	id, _ := ctx.Value(requestCorrelationIDKey{}).(string)
	return id
}

// validRequestCorrelationID accepts only the lowercase UUID form generated by
// the refresh tracer. This prevents arbitrary caller/header text from reaching
// production log fields and keeps the field bounded.
func validRequestCorrelationID(id string) bool {
	if len(id) != 36 {
		return false
	}
	for i := 0; i < len(id); i++ {
		if i == 8 || i == 13 || i == 18 || i == 23 {
			if id[i] != '-' {
				return false
			}
			continue
		}
		ch := id[i]
		if (ch < '0' || ch > '9') && (ch < 'a' || ch > 'f') {
			return false
		}
	}
	return true
}
